### ISSUE TITLE
Access to Elastic by Authorization headers

### ISSUE THREAD

**Issue by MurzNN** [elastic/xk6-output-elasticsearch#12]
Now to configure the access to Elastic, seems we can only specify the user and password.

But many projects use HTTP headers to authenticate, like `Authorization=Bearer G29l5OjyPSYfxXXXX`.

It is much more secure than the current way with the User and Password.

Could you please add this way of authorization? Thanks!

**Comment by danielmitterdorfer** [comment]
I've added support for both API keys and service account tokens in https://github.com/elastic/xk6-output-elasticsearch/pull/15. Please see the updated README on how to use these authentication mechanisms.
