### ISSUE TITLE
Allow to customize the `k6-metrics` index name

### ISSUE THREAD

**Issue by MurzNN** [elastic/xk6-output-elasticsearch#17]
When we use a single Elastic instance for several projects, it's better to have different index names per project. But currently we have a hardcoded `k6-metrics` index name in the code here
https://github.com/elastic/xk6-output-elasticsearch/blob/dcedf0c6310c9a5e990ecf72e01387af761bf144/pkg/esoutput/esoutput.go#L127C12-L127C22

So, will be good to allow configuring the index name by an env variable or/and via a command line parameter.

**Comment by danielmitterdorfer** [comment]
I understand where you're coming from. I actually wonder whether it would be sufficient to use the tagging functionality instead that you proposed in https://github.com/elastic/xk6-output-elasticsearch/issues/18. It's actually preferable to have less but larger indices in Elasticsearch. In the Elasticsearch team we run benchmarks with [Rally](https://github.com/elastic/rally) which also uses Elasticsearch as a backend. We have many different benchmark environments that developers on the team can spin up adhoc. Each environment gets a unique id and the regularly running benchmarks have their own well-known id ("nightly").  All data ends up in one metrics store (and in the same index) and never had any issues with that. Does that work for you as well?

**Comment by rooch84** [comment]
I think there are two separate issues here.  I agree with your best practices, but it would still be useful to specify the index name (via an env var).  Some teams use specific naming conventions for their indices, so it would be good to match in with those.

**Comment by MurzNN** [comment]
Yes, also the security context, sometimes we need to isolate access to the index per team, so different indexes would be a solution.

**Comment by danielmitterdorfer** [comment]
This is now possible by specifying the index name via the environment variable `K6_ELASTICSEARCH_INDEX_NAME`.
