### ISSUE TITLE
Allow to add additional custom fields to the uploaded metrics

### ISSUE THREAD

**Issue by MurzNN** [elastic/xk6-output-elasticsearch#18]
Now we have a build in list of fields, which uploads to Elastic. But when we run several different tests, it will be useful to mark each test (or group of tests) by a specific key via an additional field.

Could you extend the implementation to allow adding custom fields to the uploading data, like:
```
TestGroup=OrdersListPerformance
TestType=RandomRequestsOrder
```
and
```
TestGroup=HomepagePerformance
TestType=NoCaching
```

**Comment by danielmitterdorfer** [comment]
That's a good idea. I'll look into it (might not happen immediately though; this is somewhat of a side project of mine :)).

**Comment by danielmitterdorfer** [comment]
That's already built into k6, see [user docs on tags and groups](https://k6.io/docs/using-k6/tags-and-groups/). If you add e.g. `--tag test-group=daily` to the k6 CLI invocation this will show up in the metrics store:

```json
{
            "expected_response" : "true",
            "group" : "",
            "method" : "GET",
            "name" : "https://httpbin.test.k6.io/status/200",
            "proto" : "HTTP/1.1",
            "scenario" : "default",
            "status" : "200",
            "test-group" : "daily",
            "tls_version" : "tls1.3",
            "url" : "https://httpbin.test.k6.io/status/200"
}
```

Hence, there is nothing to do in the Elasticsearch output and I'll close this issue.

**Comment by MurzNN** [comment]
The problem is that all tags and groups are prefixed by the "SampleTags" and "MetricTags" prefixes, so we can't put the full desired field name using it, that is not very convenient.
But ok, let's do not overcomplicate the module ;)
