### ISSUE TITLE
What is the significance of SampleTags? Can they be filtered out?

### ISSUE THREAD

**Issue by abhisheksaraiya** [elastic/xk6-output-elasticsearch#20]
I see that the created index has `MetricTags` and `SampleTags`. What is the significance of `SampleTags`? Can we stop it from flowing to elastic?

**Comment by danielmitterdorfer** [comment]
Thanks for the report. That might be a bug. I'll look into this soon.

**Comment by danielmitterdorfer** [comment]
This will be fixed by #21. I've also decided to simplify the name and renamed the property to `Tags`. So in the future `MetricTags` *and* `SampleTags` will be gone and the output will only write `Tags`.
