### ISSUE TITLE
[indices:admin/create] is unauthorized for user

### ISSUE THREAD

**Issue by mujamil90** [elastic/xk6-output-elasticsearch#27]
Hi,

I am using this extension to integrate K6 tests with our organization's Elastic search's instance. I have already integrated with locally hosted ES as per the README.md file. I am getting below error when creating index in ES after test execution.
 

![Error_ES_Index](https://github.com/elastic/xk6-output-elasticsearch/assets/4981761/fc6d23e9-0fb5-4def-8961-c00a412d5e56)

I have provided details like K6_ELASTICSEARCH_URL, K6_ELASTICSEARCH_USER and K6_ELASTICSEARCH_PASSWORD inside K6 service in docker-compose.yml file. You can see it below:

> k6:
>     build: .
>     ports:
>       - "6565:6565"
>     environment:
>       - K6_OUT=output-elasticsearch
>       - K6_ELASTICSEARCH_URL=my_org_es_url
>       - K6_ELASTICSEARCH_USER=performance_test
>       - K6_ELASTICSEARCH_PASSWORD=xyz
>       - K6_ELASTICSEARCH_INDEX_NAME=filebeat-k6-metrics
>       - K6_ELASTICSEARCH_INSECURE_SKIP_VERIFY=true

**Note:** User already has permission to create index.

**Comment by danielmitterdorfer** [comment]
Can you please run the following command and paste the output here?

```
curl -s -k -u $K6_ELASTICSEARCH_USER:$K6_ELASTICSEARCH_PASSWORD -X POST "$K6_ELASTICSEARCH_URL/_security/user/_has_privileges?pretty" -H 'Content-Type: application/json' -d' 
{
  "index": [
    {
      "names": [
        "filebeat-k6-metrics"
      ],
      "privileges": [
        "write", "create_index"
      ]
    }
  ]
}'
```

I'm assuming here that K6_ELASTICSEARCH_URL looks something like "https://my-host-name:9200". Please modify the example above accordingly.

The output should similar to:

```json
{
  "username" : "elastic-admin",
  "has_all_requested" : true,
  "cluster" : { },
  "index" : {
    "filebeat-k6-metrics" : {
      "create_index" : true,
      "write" : true
    }
  },
  "application" : { }
}
```

Specifically `has_all_requested` must be `true` otherwise that user does not have sufficient permissions.

**Comment by mujamil90** [comment]
I have have sent curl request with port and without port _has_all_requested_ is _false_ in both case. After checking with responsible person I found that User has rights but pattern for Index is started with "performancetest-*". Now I can see _has_all_requested_ is _true_
![curl_check_user_access](https://github.com/elastic/xk6-output-elasticsearch/assets/4981761/a3f40a6b-813b-4bb8-b413-19a65eb1e4cd)

And I am not getting any error.
Thank you for quick reply.

**Comment by danielmitterdorfer** [comment]
Great it works now and thanks for the follow-up! Closing now as your issue is resolved.
