### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gabrielfsousa** [elastic/xk6-output-elasticsearch#7]
how can we skip tls verification ?

**Comment by danielmitterdorfer** [comment]
Did you try `export K6_ELASTICSEARCH_INSECURE_SKIP_VERIFY=true` before starting k6? See also the [example in the README](https://github.com/elastic/xk6-output-elasticsearch#running-a-local-cluster).

**Comment by danielmitterdorfer** [comment]
No feedback; closing. If the issue still persists, please reopen.
