### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [elastic/xk6-output-elasticsearch#8]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add the xk6 topic to your repository metadata
* add an `examples` directory containing k6 test scripts making use of your extension
* requires at least one versioned release

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by danielmitterdorfer** [comment]
Thanks for the ping. I'm gonna look into this within the next days.

**Comment by danielmitterdorfer** [comment]
I've:

* added the `k6` topic
* Made sure we have an `examples` directory in #9 (we had a `samples` directory before which I've renamed)
* Created a [versioned release](https://github.com/elastic/xk6-output-elasticsearch/releases/tag/v0.1.0)

So I believe we should be all set and will close this issue. Please let me know if there's anything else in case I have missed something unintentionally.

**Comment by javaducky** [comment]
@danielmitterdorfer , this looks perfect, thank you so much!

**Comment by danielmitterdorfer** [comment]
Great! You're welcome. :slightly_smiling_face:
